# checks for GitHub Actions updates
version: 2
updates:
  
  - package-ecosystem: "github-actions"
    directory: "/"
    
    # trigger at 4:25 AM EST every day
    schedule:
      
      interval: "daily"
      time: "04:25"
      timezone: "America/New_York"
