# checks for GitHub Actions updates
version: 2
updates:
  
  - package-ecosystem: "github-actions"
    directory: "/"
    
    # trigger at 2:25 AM EST every day
    schedule:
      
      cron: "25 2 * * *"
      timezone: "America/New_York"
