# trigger GitHub Actions updates at 2:25 AM EST every day
version: 2
updates:

  # Monday through Friday check
  - package-ecosystem: "github-actions"
    directory: "/"
    
    schedule:
      
      interval: "daily"
      time: "02:25"
      timezone: "America/New_York"

  # Saturday check
  - package-ecosystem: "github-actions"
    directory: "/"
    
    schedule:
      
      interval: "weekly"
      day: "saturday"
      time: "02:25"
      timezone: "America/New_York"

  # Sunday check
  - package-ecosystem: "github-actions"
    directory: "/"
    
    schedule:
      
      interval: "weekly"
      day: "sunday"
      time: "02:25"
      timezone: "America/New_York"
